sudo: false
cache: bundler

language: ruby
rvm:
  - 2.2.4

services: mysql

before_script:
  - bundle exec rake app:db:create
  - bundle exec rake app:db:migrate

script:
  - bundle exec rake app:spec

notifications:
  recipients:
    - martin@trustarts.org
  slack: trustarts:FrVc7H8dDadhctfZ7NvHTZES
