development:
  adapter: mysql2
  database: convoy_master_development
  username: root
  password:
  host: localhost

test: &TEST
  adapter: mysql2
  database: convoy_master_test
  username: root
  password:
  host: localhost
